-- lute-lint-global-ignore(unused_variable)
local stream = require("@lute/stream")

local fs = {}

export type FileType = "file" | "dir" | "link" | "fifo" | "socket" | "char" | "block" | "unknown"
export type HandleMode = "r" | "w" | "x" | "a" | "r+" | "w+" | "x+" | "a+"

export type FileMetadata = {
	type: FileType,
	permissions: { readonly: boolean },
	size: number,
	created: any,
	accessed: any,
	modified: any,
}

export type DirectoryEntry = {
	name: string,
	type: FileType,
}

export type WatchHandle = {
	close: (self: WatchHandle) -> (),
}

export type WatchEvent = {
	change: boolean,
	rename: boolean,
}

function fs.open(path: string, mode: HandleMode?): stream.Stream
	error("not implemented")
end

function fs.remove(path: string): ()
	error("not implemented")
end

function fs.stat(path: string): FileMetadata
	error("not implemented")
end

function fs.type(path: string): FileType
	error("not implemented")
end

--- Creates a directory at the specified path.
--- To set the permissions mode for a directory (Unix only), see @std/process for `run` or `system` to shell out to `chmod` or the equivalent.
function fs.mkdir(path: string): ()
	error("not implemented")
end

function fs.link(src: string, dest: string): ()
	error("not implemented")
end

function fs.symlink(src: string, dest: string): ()
	error("not implemented")
end

function fs.watch(path: string, callback: (filename: string, event: WatchEvent) -> ()): WatchHandle
	error("not implemented")
end

function fs.exists(path: string): boolean
	error("not implemented")
end

function fs.copy(src: string, dest: string): ()
	error("not implemented")
end

function fs.listdir(path: string): { DirectoryEntry }
	error("not implemented")
end

function fs.rmdir(path: string): ()
	error("not implemented")
end

return fs
